import { describe, expect, it } from "vitest";
import { generateCoinSide } from "../src/logic/flipCoin";

type CoinCounts = {
  sampleSize: number;
  upright: number;
  uprightPercentage: number;
  reversed: number;
  reversedPercentage: number;
  uprightDeviationPercentagePoints: number;
};

function rounded(value: number, digits = 4): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

function simulate(sampleSize: number): CoinCounts {
  let upright = 0;
  for (let index = 0; index < sampleSize; index += 1) {
    if (generateCoinSide() === "heads") upright += 1;
  }
  const reversed = sampleSize - upright;
  const uprightPercentage = upright / sampleSize * 100;
  return {
    sampleSize,
    upright,
    uprightPercentage: rounded(uprightPercentage),
    reversed,
    reversedPercentage: rounded(100 - uprightPercentage),
    uprightDeviationPercentagePoints: rounded(uprightPercentage - 50),
  };
}

function simulateFiveCardGroups(groupCount: number) {
  const reversedCountDistribution = Array.from({ length: 6 }, () => 0);
  for (let groupIndex = 0; groupIndex < groupCount; groupIndex += 1) {
    let reversedInGroup = 0;
    for (let cardIndex = 0; cardIndex < 5; cardIndex += 1) {
      if (generateCoinSide() === "tails") reversedInGroup += 1;
    }
    reversedCountDistribution[reversedInGroup] += 1;
  }
  return reversedCountDistribution.map((groups, reversedCards) => ({
    reversedCards,
    groups,
    percentage: rounded(groups / groupCount * 100),
    theoreticalPercentage: rounded(([1, 5, 10, 10, 5, 1][reversedCards] / 32) * 100),
  }));
}

describe("production orientation RNG audit", () => {
  it("prints read-only audit samples generated by the production function", () => {
    const sampleRuns = [1_000, 10_000, 100_000, 1_000_000].map(simulate);
    const repeatedRuns = Array.from({ length: 10 }, (_, run) => ({
      run: run + 1,
      ...simulate(100_000),
    }));
    const fiveCardGroups = simulateFiveCardGroups(100_000);

    console.log("ORIENTATION_RNG_AUDIT=" + JSON.stringify({
      generatedAt: new Date().toISOString(),
      sourceFunction: "src/logic/flipCoin.ts#generateCoinSide",
      sampleRuns,
      repeatedRuns,
      fiveCardGroups: {
        groupCount: 100_000,
        distribution: fiveCardGroups,
      },
    }, null, 2));

    expect(sampleRuns).toHaveLength(4);
    expect(repeatedRuns).toHaveLength(10);
    expect(fiveCardGroups.reduce((sum, row) => sum + row.groups, 0)).toBe(100_000);
  }, 120_000);
});
